- name: "Add repository for PHP 7.0."
  apt_repository: 
    repo: "ppa:ondrej/php" 
    update_cache: yes
- name: install lamp - apache, mysql, php - may take a while to install
  apt: 
    name:
      - apache2
      - php7.0-common
      - php7.0-cli
      - php7.0-dev
      - php7.0-gd
      - php7.0-json
      - php7.0-mcrypt
      - php7.0-mysql
      - mysql-server
    state: present
    update_cache: true
- name: print sample commands to run inside the host
  debug:
    msg: 
      - "a few commands to verify all servers are ready:"
      - "apache: simply visit {{ ansible_default_ipv4.address }}"
      - "mysql:  mysql -u root -p"

- include: db.yml
